# docker-compose.override.yml (Extended config for DEVELOPMENT)
version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: ./app
    environment:
      NODE_ENV: 'dev'
    volumes:
      - ./app/src:/app/src
  
  proxy:
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf